name: Sukka Friends

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: bun i
    - run: bun run build
    - run: cp -r src/img dist/img
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dist
        user_name: ${{ secrets.GIT_USERNAME }}
        user_email: ${{ secrets.GIT_EMAIL }}
        cname: friends.skk.moe
